# Generated by Django 3.2.25 on 2025-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffId',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('ph_no', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('dob', models.DateField()),
                ('photo', models.CharField(max_length=550)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'staff_id',
                'managed': False,
            },
        ),
    ]
