# Generated by Django 3.2.25 on 2025-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTb',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=45)),
                ('contact_name', models.CharField(max_length=45)),
                ('remark', models.CharField(max_length=45)),
                ('job_id', models.IntegerField()),
                ('mail', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
        ),
    ]
