# Generated by Django 3.2.25 on 2025-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegTb',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('ph_no', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('photo', models.CharField(max_length=45)),
                ('dob', models.DateField(db_column='DOB')),
                ('interest', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('hobbies', models.CharField(max_length=45)),
                ('cv', models.CharField(max_length=45)),
                ('cert_id', models.IntegerField()),
                ('adrees', models.CharField(max_length=45)),
                ('pincode', models.CharField(max_length=45)),
                ('qualification', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
